config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    def light?
        calories < 100
    end

    def self.created_at
        where('created_at <= ?', Time.now).order('created_at desc')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @recipes = Recipe.created_at
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end

    def update
        @recipe = Recipe.find(params[:id])        
        @recipe.update(recipe_params)
        redirect_to @recipe
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.save
        redirect_to @recipe
    end

    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy

        redirect_to recipes_url
    end

    private
    def recipe_params
        params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :cost,
        :kind, :portion, :duration, :poster)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
    def formata_caloria(recipe)
        if recipe.light?
            content_tag(:strong, "Light (menos de 100 calorias)")
        else
            recipe.calories
        end
    end

    def imagem(recipe)
        if recipe.poster.blank?
            image_tag('foto-nao-disponivel.jpeg')
        else
            image_tag(recipe.poster)
        end
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <p class="text-muted">Receitas fácil com Receitasnet.</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%= link_to image_tag('receitanet.png', size: 30, alt: 'receitanet'), root_path,
        class: 'navbar-brand' %>
        <%= link_to 'Receitasnet', root_path, class: 'navbar-brand' %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSuppotedContent"
        aria-expand="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Receitasnet', root_path %></li>
        </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receitasnet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_pack_tag 'media/images/receitanet.png' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
    <p><%= f.label :Nome %></p>
    <p><%= f.text_field :name %></p>

    <p><%= f.label :Ingredientes %></p>
    <p><%= f.text_area :stuff, cols: 30, rows: 10 %></p>
    
    <p><%= f.label :Tipo %></p>
    <p><%= f.text_field :kind %></p>

    <p><%= f.label :Calorias %></p>
    <p><%= f.number_field :calories %></p>

    <p><%= f.label :Modo_de_preparo %></p>
    <p><%= f.text_area :prepare_mode, cols: 30, rows: 10 %></p>

    <p><%= f.label :Tempo_de_Preparo %></p>
    <p><%= f.time_select :duration %>

    <p><%= f.label :Porcões %></p>
    <p><%= f.text_field :portion %></p>

    <p><%= f.label :Custo %></p>
    <p><%= f.number_field :cost %></p>

    <p><%= f.label :Poster %></p>
    <p><%= f.text_field :poster, placeholder: '.GIF, .JPEG OU .PNG' %></p>

    <p>
        <%= f.submit %>
        <%= link_to 'Cancelar', root_path %>
    </p>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editando Receitas</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 style="font-size: 30px">
                <%= pluralize(@recipes.size, 'Receita', 'Receitas') %>
                <small class="nova_receita" style="font-size: 25px">
                    <%= link_to 'Nova Receita', new_recipe_path %>
                </small>
            </h1>
        </div>
    </div>

    <% @recipes.each do |recipe| %>
        <div class="row align-items-center">
            <div class="col">
                <%= link_to imagem(recipe), recipe %>
            </div>
            <div class="col mb-5">
                <h3><%= link_to recipe.name, recipe %></h3>
                <p><%= truncate(recipe.stuff, length: 15, separator: ' ') %></p>

                <h4>Calorias:</h4>
                <p><%= formata_caloria(recipe) %></p>

                <h4>Tempo de Preparo</h4>
                <p><%= recipe.duration.to_formatted_s(:time) %></p>

                <h4>Custo:</h4>
                <p><%= recipe.cost %></p>
            </div>
        </div>
    <% end %>
</div>

app/views/recipes/new.html.erb
<h1>Criando Receitas</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<article>
    <header>
        <h1><%= @recipe.name %></h1>
        <%= imagem(@recipe) %>
    </header>

    <h2>Tipo</h2>
    <p><%= @recipe.kind %></p>
    
    <h2>Ingredientes</h2>
    <p><%= @recipe.stuff %></p>
    
    <h2>Calorias</h2>
    <p><%= @recipe.calories %></p>
    
    <h3>Modo de preparo</h3>
    <p><%= @recipe.prepare_mode %></p>

    <h3>Tempo de Preparo</h3>
    <p><%= @recipe.duration.to_formatted_s(:time) %> min</p>

    <h3>Porções</h3>
    <p><%= pluralize(@recipe.portion, 'porção', 'porções') %></p>

    <h3>Custo</h3>
    <p><%= @recipe.cost %></p>
</article>

<%= link_to 'Receitas', recipes_path %>
<%= link_to 'Editar Receita', edit_recipe_path(@recipe) %>
<%= link_to 'Deletar Receita', recipe_path(@recipe), method: :delete,
data: { confirm: 'Você tem certeza que deseja Deletar?' } %>